### ISSUE TITLE
NPM latest version tag lists 0.9.1

### ISSUE THREAD

**Issue by Flamov** [gucong3000/postcss-syntax#16]
Hi all,

I have two packages that are requesting 0.10.0 of _postcss-syntax_ as a dependency, _postcss-html_ and _postcss-markdown_.

I see the [latest release](https://github.com/gucong3000/postcss-syntax/releases/tag/v0.10.0) of _postcss-syntax_ on GitHub is 0.10.0, but the [latest version listed on NPM](https://www.npmjs.com/package/postcss-syntax) is 0.9.1. Although I do see 0.10.0 in the [version history](https://www.npmjs.com/package/postcss-syntax), it seems to be superseded by 0.9.1.

This is causing issues with _npm install_ right now, however it does work with downgrading certain NPM packages. Would it be possible to bump up the latest version on NPM?

Error log:

```
217 error node v4.4.4
218 error npm  v2.15.1
219 error code EPEERINVALID
220 error peerinvalid The package postcss-syntax@0.9.1 does not satisfy its siblings' peerDependencies requirements!
220 error peerinvalid Peer postcss-html@0.23.7 wants postcss-syntax@^0.10.0
220 error peerinvalid Peer postcss-markdown@0.23.7 wants postcss-syntax@^0.10.0
```

Many thanks in advance! :)

**Comment by gucong3000** [comment]
v0.9.1 is a hotfix for v0.9.0, and it is not support for npm@2, please update to v0.10.0.
