### ISSUE TITLE
documentation `syntax.config = defaultConfig`

### ISSUE THREAD

**Issue by evilebottnawi** [gucong3000/postcss-syntax#27]
Why? We use `lint-staged` and will be great have example how we can use regexp's in config, example:

**lint-staged.config.js**
```js
const postcssSyntax = require("postcss-syntax");

const cssRegExp = /* Logic for concatenate regexps */;

module.exports = {
  linters: {
     cssRegExp: ["stylelint", "git add"]
  }
};
```

Or export all supported extensions. In stylelint@10 we can implement zero configuration for CLI, like:
```
stylelint . -i .gitignore
```

Now (in stylelint@9) using `.` throw error on unsupported extensions (example json). In stylelint@10 we can fix it, also provide easy integration with `lint-staged`

**Comment by gucong3000** [comment]
In `postcss-syntax@0.30.0`, regexp was move to:
https://github.com/gucong3000/postcss-syntax/blob/695e0e82120ba49807fe593837761e375c6c7641/get-lang.js#L12-L34

**Comment by gucong3000** [comment]
Example for use regexp in config:
https://github.com/gucong3000/postcss-syntax/#use-cases

**Comment by evilebottnawi** [comment]
@gucong3000 it is hard to use this in `lint-staged`, `lint-staged` use glob, will be great exports extensions what supported `postcss-syntax`

**Comment by gucong3000** [comment]
I got a so lang glob form `testcase/test/languages.js`
```bash
**/*.{acss,asp,aspx,css,ejs,es6,htm,html,js,jshtm,jsp,jsx,markdn,markdown,md,mdoc,mdown,mjs,mkd,pac,pcss,php,postcss,rhtml,shtml,ts,tsx,ux,volt,vue,wpy,wxss,xhtml,xsl,xslt}
```

**Comment by evilebottnawi** [comment]
@gucong3000 Can we export this as part of api `postcss-syntax`?

**Comment by gucong3000** [comment]
I think that might be it.
```js
// postcss-syntax@0.31.0
var extensions = require("postcss-syntax/package.json").extensions
```

**Comment by gucong3000** [comment]
```js
var getLang = require("postcss-syntax/get-lang")
console.log(getLang("a.unknow", "const a = require('a')"));  // {extract: "jsx"}
console.log(getLang("a.mjs", ""));  // {extract: "jsx"}
console.log(getLang("a.css", ""));  // {lang: "css"}
console.log(getLang("a.sss", ""));  // {lang: "sugarss"}
```
